from __future__ import annotations

from typing import Mapping
from typing import Sequence

from pydantic import ValidationError

from app.enterprise_authorization_evidence import (
    EnterpriseGroupMembershipUnavailable,
    ValidatedEnterpriseToken,
    require_authoritative_group_ids,
)

from app.enterprise_identity import EnterpriseIdentity

from app.enterprise_principal_binding import (
    EnterprisePrincipalBinding,
    build_enterprise_principal,
    load_enterprise_principal_bindings,
)

from app.enterprise_tenant_binding import (
    EnterpriseTenantBinding,
    load_enterprise_tenant_bindings,
    resolve_enterprise_tenant,
)

from app.security_context import SecurityContext

from app.retrieval_authorization import (
    RetrievalPrincipal,
)


# -------------------------------------------------
# CONTEXT FAILURE
# -------------------------------------------------


class EnterpriseSecurityContextError(
    RuntimeError
):
    """
    Raised when trusted enterprise identity state cannot be
    converted into a valid immutable SecurityContext.
    """


# -------------------------------------------------
# BUILD TRUSTED SECURITY CONTEXT
# -------------------------------------------------


def build_enterprise_security_context(
    identity: EnterpriseIdentity,
    *,
    session_id: str,
    principal_bindings: Sequence[
        EnterprisePrincipalBinding
    ],
    tenant_bindings: Sequence[
        EnterpriseTenantBinding
    ],
) -> SecurityContext:
    """
    Build SecurityContext from one validated enterprise
    identity.

    Both Principal authorization and internal tenant scope are
    derived from the same EnterpriseIdentity. Callers cannot
    independently combine identity, Principal, or tenant
    authority.

    session_id is expected to be generated by trusted server
    session logic rather than supplied as an authorization
    claim by a client or model.
    """

    if (
        not isinstance(
            session_id,
            str,
        )
        or not session_id.strip()
        or session_id != session_id.strip()
    ):
        raise EnterpriseSecurityContextError(
            "Trusted enterprise session identity is invalid."
        )

    principal = build_enterprise_principal(
        identity,
        bindings=
            principal_bindings,
    )

    tenant_id = resolve_enterprise_tenant(
        identity,
        bindings=
            tenant_bindings,
    )

    try:

        return SecurityContext.from_principal(
            principal,
            tenant_id=tenant_id,
            session_id=session_id,
        )

    except ValidationError as exc:

        raise EnterpriseSecurityContextError(
            "Trusted enterprise security context "
            "could not be established."
        ) from exc


# -------------------------------------------------
# RESOLVE FROM SERVER CONFIGURATION
# -------------------------------------------------


def resolve_enterprise_security_context(
    identity: EnterpriseIdentity,
    *,
    session_id: str,
    environment: Mapping[str, str] | None = None,
) -> SecurityContext:
    """
    Resolve the complete authenticated and authorized
    enterprise SecurityContext from trusted server-side
    configuration.

    The same validated identity drives both application
    Principal binding and internal tenant mapping.
    """

    principal_bindings = (
        load_enterprise_principal_bindings(
            environment
        )
    )

    tenant_bindings = (
        load_enterprise_tenant_bindings(
            environment
        )
    )

    return build_enterprise_security_context(
        identity,
        session_id=session_id,
        principal_bindings=
            principal_bindings,
        tenant_bindings=
            tenant_bindings,
    )


# -------------------------------------------------
# ENTERPRISE RETRIEVAL AUTHORITY
# -------------------------------------------------


def build_enterprise_retrieval_principal_from_validated_token(
    validated_token: ValidatedEnterpriseToken,
    *,
    session_id: str,
    principal_bindings: Sequence[
        EnterprisePrincipalBinding
    ],
    tenant_bindings: Sequence[
        EnterpriseTenantBinding
    ],
) -> RetrievalPrincipal:
    """
    Build one immutable retrieval authorization principal
    from the same cryptographically validated enterprise
    token used to establish identity.

    SecurityContext remains execution-only.

    Group membership is attached directly to the retrieval
    authority boundary only when membership is complete or
    Graph-resolved.

    Missing or incomplete group authority is represented as
    group_ids=None and therefore cannot authorize a
    group-protected document.
    """

    context = (
        build_enterprise_security_context(
            validated_token.identity,
            session_id=session_id,
            principal_bindings=
                principal_bindings,
            tenant_bindings=
                tenant_bindings,
        )
    )

    try:

        group_ids = (
            require_authoritative_group_ids(
                validated_token.authorization
            )
        )

    except EnterpriseGroupMembershipUnavailable:

        group_ids = None

    return RetrievalPrincipal(
        principal_id=
            context.principal_id,
        tenant_id=
            context.tenant_id,
        retrieval_access=
            context.retrieval_access,
        group_ids=
            group_ids,
    )


def resolve_enterprise_retrieval_principal_from_validated_token(
    validated_token: ValidatedEnterpriseToken,
    *,
    session_id: str,
    environment: Mapping[str, str] | None = None,
) -> RetrievalPrincipal:
    """
    Resolve Principal policy, internal tenancy, and complete
    enterprise group membership from one validated-token
    authority boundary.

    No caller-selected group IDs are accepted.
    """

    principal_bindings = (
        load_enterprise_principal_bindings(
            environment
        )
    )

    tenant_bindings = (
        load_enterprise_tenant_bindings(
            environment
        )
    )

    return (
        build_enterprise_retrieval_principal_from_validated_token(
            validated_token,
            session_id=session_id,
            principal_bindings=
                principal_bindings,
            tenant_bindings=
                tenant_bindings,
        )
    )
